export enum Tool {
  Summarizer = 'Summarizer',
  ImageGenerator = 'ImageGenerator',
  JsonFormatter = 'JsonFormatter',
  ColorConverter = 'ColorConverter',
  PasswordGenerator = 'PasswordGenerator',
  BmiCalculator = 'BmiCalculator',
  ExchangeRateCalculator = 'ExchangeRateCalculator',
  PercentageCalculator = 'PercentageCalculator',
  AgeCalculator = 'AgeCalculator',
  BarcodeGenerator = 'BarcodeGenerator',
  QrCodeGenerator = 'QrCodeGenerator',
  NicknameGenerator = 'NicknameGenerator',
  MealPicker = 'MealPicker',
  DdayCalculator = 'DdayCalculator',
  CagrCalculator = 'CagrCalculator',
  UnitConverter = 'UnitConverter',
  LoanCalculator = 'LoanCalculator',
  About = 'About',
  TermsOfService = 'TermsOfService',
  PrivacyPolicy = 'PrivacyPolicy',
}